var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/onboarding/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6112f204._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00b1957a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/src_app_ca777385._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a8b9a7ab._.js")
R.c("server/chunks/ssr/_a2985d5b._.js")
R.c("server/chunks/ssr/_86419d3c._.js")
R.m(76924)
R.m(61905)
module.exports=R.m(61905).exports
